### ISSUE TITLE
Update content of /brand/colour-palette

### ISSUE THREAD

**Issue by yaili** [canonical-web-and-design/design.ubuntu.com-design#6]
The existing page http://design.ubuntu.com/brand/colour-palette mentions some things which are deprecated or incorrect. Some of the things which need to be reviewed/changed:
- Black in the core colours
- References to audiences sliders
- References to colours meaning enterprise/community
- Warm grey - not used anymore
- Dots
- It's missing secondary palette
- It's missing latest colour research findings
- Greys not up to date
- Are tints correct?

Make sure that this is done in a Google Doc in the project folder, following the same format as the other pages.

**Comment by marcush** [comment]
I will do this next week 10/07

**Comment by pmahnke** [comment]
this has been completed between https://docs.vanillaframework.io/en/settings/color-settings and https://design.ubuntu.com/brand/colour-palette/ and will be looked at again this cycle, closing   thanks @yaili
